"""Generate docs/CHECKS.md from the check registry (single source of truth).

Usage: python scripts/generate_docs.py          # rewrite the file
       python scripts/generate_docs.py --check  # exit 1 if the file is stale (used by tests)
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cloudposture.checks import REGISTRY  # noqa: E402
from cloudposture.models import CIS, FRAMEWORKS, ISO27001, PCI_DSS, SOC2  # noqa: E402

OUT = ROOT / "docs" / "CHECKS.md"


def render() -> str:
    specs = sorted((rc.spec for rc in REGISTRY.values()), key=lambda s: s.id)
    lines = [
        "# Implemented checks",
        "",
        "<!-- GENERATED by scripts/generate_docs.py from the check registry - do not edit by hand. -->",
        "",
        f"{len(specs)} checks. CIS references target **{FRAMEWORKS[CIS]}**. "
        "`exact` = the CIS recommendation tests the same condition; `approximate` = thematic link. "
        "ISO 27001 / PCI DSS / SOC 2 links are always `approximate` - see [MAPPINGS.md](MAPPINGS.md).",
        "",
        "| ID | Service | Severity | Check | CIS | ISO 27001 | PCI DSS | SOC 2 |",
        "|----|---------|----------|-------|-----|-----------|---------|-------|",
    ]

    def cell(spec, fw):
        return "<br>".join(m.label() for m in spec.mappings.get(fw, [])) or "-"

    for s in specs:
        lines.append(f"| {s.id} | {s.service} | {s.severity.value} | {s.title} | {cell(s, CIS)} | "
                     f"{cell(s, ISO27001)} | {cell(s, PCI_DSS)} | {cell(s, SOC2)} |")
    lines += ["", "## Details", ""]
    for s in specs:
        lines += [f"### {s.id} - {s.title}", "",
                  f"- **Service / severity:** {s.service} / {s.severity.value}",
                  f"- **Why:** {s.description}",
                  f"- **Expected state:** {s.expected}",
                  "- **Remediation:**", *[f"  {i}. {r}" for i, r in enumerate(s.remediation, 1)],
                  "- **Control references:**"]
        for fw, ms in s.mappings.items():
            lines += [f"  - {fw}: " + "; ".join(f"{m.control_id} {m.title} _({m.confidence})_" for m in ms)]
        if CIS not in s.mappings:
            lines += ["  - CIS: _no recommendation in v3.0.0 (extra hardening check)_"]
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else 1)
    OUT.write_text(text)
    print(f"wrote {OUT}")
